Starting execution
Inside try block
About to throw
Caught error:
Test error message
Finally block executed
Many statements
Execution complete
